### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by lcundiff** [kappys1/react-arc-text#22]
There are hundreds of errors when running npm install on my machine (Ubuntu 20.04)

Steps to reproduce: 
Run "npm i react-arc-text" on Ubuntu machine. 

Here is an example of one of the errors: 
../node_modules/nan/nan.h:2258:52: error: ‘value’ was not declared in this scope
 2258 |   NanSetTemplate(templ->PrototypeTemplate(), name, value, attributes);

Errors end with: 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/logancundiff/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.13.0-7614-generic
gyp ERR! command "/home/.nvm/versions/node/v14.17.6/bin/node" "/home/.nvm/versions/node/v14.17.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Documents/GitHub/steeply-app/node_modules/utf-8-validate
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

However, package does get installed. However, I get a module not found upon attempting to import it which I assumed was due to these errors. If it's an issue on my end, I can try to resolve it, but wanted to post it here in case others are having this issue on Ubuntu.

**Comment by lcundiff** [comment]
Realized this isn't a React Native Library. Closing issue.
